### ISSUE TITLE
Generation stopped working after updating Flutter

### ISSUE THREAD

**Issue by tobytraylor** [davidmarne/built_redux#101]
This is a lame defect because I updated flutter and i don't know what version of flutter i came from.  During that update everything broke and I never realized that i don't have a way to revert to a specific versoin of flutter.   My code that worked on that version no longer worked on the updated version due to libraries being incompatible.  After making all of the required library updates to work with the updated flutter I find myself with a version of built_value_generator that doesn't generate the files anymore.  I'm not sure though if this is the fault of built_value_generator or built_redux.  The portion of the built_redux file (actions.g.dart) that is the redux code works but the portion of the actions file that is from built_value_generator isn't there and all of the remaining *.g.dart files are not being generated.  Any help or even just guidance on how to debug something being run by build_runner.  

pubspec.yaml
```
dependencies:
  #flutter:
  #  sdk: flutter
  #flutter_localizations:
  #  sdk: flutter
  meta: ^1.0.4
  fluro: ^1.3.5
  flutter_built_redux: ^0.6.0
  built_redux: ^7.5.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  intl: any
  intl_translation: any
  path_provider: ^0.4.1
  built_redux_rx: ^0.1.2
  cloud_firestore: ^0.8.1
  cloud_functions: ^0.0.4
  firebase_auth: ^0.6.2
  firebase_dynamic_links: ^0.1.0
  google_sign_in: ^3.2.1
  rxdart: ^0.19.0
  ulid: ^1.0.1

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  #flutter_driver:
  #  sdk: flutter
  built_value_generator: ^6.1.4
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
  quiver: '>=0.21.0 <3.0.0'

dependency_overrides:
  rxdart: ^0.19.0
```

build.dart in .dart_tool
```
import 'package:build_runner/build_runner.dart' as _i1;
import 'package:built_redux/builder.dart' as _i2;
import 'package:built_value_generator/builder.dart' as _i3;
import 'package:source_gen/builder.dart' as _i4;
import 'package:build_config/build_config.dart' as _i5;
import 'dart:isolate' as _i6;

final _builders = <_i1.BuilderApplication>[
  _i1.apply('built_redux|built_redux', [_i2.builtRedux],
      _i1.toDependentsOf('built_redux'),
      hideOutput: true, appliesBuilders: ['source_gen|combining_builder']),
  _i1.apply('built_value_generator|built_value', [_i3.builtValue],
      _i1.toDependentsOf('built_value_generator'),
      hideOutput: true, appliesBuilders: ['source_gen|combining_builder']),
  _i1.apply('source_gen|combining_builder', [_i4.combiningBuilder],
      _i1.toNoneByDefault(),
      hideOutput: false, appliesBuilders: ['source_gen|part_cleanup']),
  _i1.applyPostProcess('source_gen|part_cleanup', _i4.partCleanup,
      defaultGenerateFor: const _i5.InputSet())
];
main(List<String> args, [_i6.SendPort sendPort]) async {
  var result = await _i1.run(args, _builders);
  sendPort?.send(result);
}

```
