### ISSUE TITLE
Broken with latest versions

### ISSUE THREAD

**Issue by BerndWessels** [davidmarne/built_redux#30]
Hi guys

looks like newer versions break this.

Looks like its not generating code unless you implement `implements Built<......>`.

Here is the example with your own test files:

![dart](https://user-images.githubusercontent.com/1776695/30940566-f287d620-a43d-11e7-99ee-69976e0c10c3.png)

My package yml with the latest versions:

```
name: redux_immutable_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  #flutter_built_redux: ^0.0.2
  built_redux: ^5.1.0
  built_collection: ^1.5.0
  built_value: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build: ^0.10.2
  build_runner: ^0.5.0
  built_value_generator: ^4.2.0
  source_gen: ^0.7.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
```
