### ISSUE TITLE
Mark generated code as ignored by linter

### ISSUE THREAD

**Issue by patkujawa-wf** [davidmarne/built_redux#70]
Unless we can get all the generated code to abide by all the rules.

See https://github.com/dart-lang/linter/issues/165 for some options. Perhaps just `// ignore_for_file: linter_rule` in each generated file?

**Comment by davidmarne** [comment]
So in the dart2 dev branch you can set this by setting the header option in your build.yaml

```yaml
targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: false
    builders:
      built_redux|built_redux:
        options:
          header: // ignore_for_file: linter_rule
```

However, that will only work with dart 2.

If there are any specific lints you are having issues with post them here and I can just add them to all generated files for the time being.
