### ISSUE TITLE
dart 2 dev instruction incomplete

### ISSUE THREAD

**Issue by BerndWessels** [davidmarne/built_redux#77]
Hi

the dart 2 dev instructions say `remove your old build scripts`. But they don't say what the new way to build is.

So now I have no idea what to run to build the generated files.

**Comment by BerndWessels** [comment]
@zoechi the old build.dart runs `new BuiltValueGenerator(),` and `new BuiltReduxGenerator(),` as well.

Are you sure that `flutter packages pub run build_runner build` does actually run both build actions?



This was the old script, but it is not compatible to dart 2:

```import 'dart:async';

import 'package:build_runner/build_runner.dart';
import 'package:built_value_generator/built_value_generator.dart';
import 'package:source_gen/source_gen.dart';
import 'package:built_redux/generator.dart';

Future main(List<String> args) async {
  await build([
    new BuildAction(
        new PartBuilder([
          new BuiltValueGenerator(),
          new BuiltReduxGenerator(),
        ]),
        // your lib name here
        'myapp',
        // tweak the files that invoke the generator here
        inputs: const ['lib/**/*.dart'])
  ], deleteFilesByDefault: true);
}
```

**Comment by zoechi** [comment]
You don't need a build script. Just run `build_runner` 

> `flutter packages pub run build_runner build`

You need to use recent versions of packages. 
I think `built_redux` still requires a fixed dependency to a pre-release version `built_redux: 7.4.1-dev` to work with `build_runner` (not sure though)

**Comment by BerndWessels** [comment]
Thanks a lot.

These depenencies seem to work with the `dev channel`:

```
dependencies:
  flutter:
    sdk: flutter
  # redux
  flutter_built_redux: ^0.5.0
  built_redux: 7.4.1-dev
  built_value: ^5.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  #firebase
  firebase_core: ^0.2.3
  cloud_firestore: ^0.7.2

dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  # redux
  build_runner: ^0.8.0
  built_value_generator: ^5.2.0
  source_gen: ^0.7.0
```

Notice that I had to comment out the `flutter_test` dependency - otherwise it fails.
